# Generated by Django 3.1.4 on 2020-12-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floresta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_floresta', models.CharField(max_length=200)),
                ('cultura_floresta', models.CharField(max_length=200)),
                ('especie_floresta', models.CharField(max_length=200)),
                ('estado_floresta', models.CharField(max_length=200)),
                ('area_floresta', models.IntegerField()),
            ],
        ),
    ]
